// 03-Jun bug — Account-create dropdown vocabularies. All sourced verbatim
// from the bug tracker Expected fields.

export const INDUSTRY_OPTIONS = [
  "Professional Services",
  "Food Products",
  "Electrical Equipment",
  "Pharmaceuticals",
  "Beverages",
  "Construction & Engineering",
  "Banks",
  "IT Services",
  "Commercial Services & Supplies",
  "Chemicals",
  "Health Care Equipment & Supplies",
  "Hotels, Restaurants & Leisure",
  "Aerospace & Defense",
  "Financial Services",
  "Machinery",
  "Containers & Packaging",
  "Gas Utilities",
  "Software",
  "Water Utilities",
  "Biotechnology",
  "Semiconductors & Semiconductor Equipment",
  "Metals & Mining",
  "Construction Materials",
  "Electronic Equipment, Instruments & Components",
  "Marine Transportation",
  "Health Care Providers & Services",
  "Distributors",
  "Oil, Gas & Consumable Fuels",
  "Personal Care Products",
  "Insurance",
  "Capital Markets",
  "Broadline Retail",
  "Automobiles",
  "Health Care Technology",
  "Household Durables",
  "Consumer Finance",
  "Diversified Telecommunication Services",
  "Real Estate Management & Development",
  "Building Products",
  "Technology Hardware, Storage & Peripherals",
  "Independent Power and Renewable Electricity Producers",
  "Consumer Staples Distribution & Retail",
  "Interactive Media & Services",
  "Automobile Components",
  "Specialty Retail",
  "Ground Transportation",
  "Air Freight & Logistics",
  "Wireless Telecommunication Services",
  "Passenger Airlines",
  "Electric Utilities",
  "Media",
  "Multi-Utilities",
  "Industrial Conglomerates",
  "Paper & Forest Products",
  "Textiles, Apparel & Luxury Goods",
  "Energy Equipment & Services",
  "Diversified Consumer Services",
  "Tobacco",
  "Household Products",
  "Life Sciences Tools & Services",
  "Entertainment",
  "Household Goods",
  "Leisure Products",
  "Trading Companies & Distributors",
  "Other",
] as const;

export const TIER_OPTIONS = ["Tier 1", "Tier 2", "Tier 3"] as const;
export const ACCOUNT_TYPE_OPTIONS = ["Hypergrowth", "Standard", "Retention"] as const;

export const COMMERCIAL_OWNER_OPTIONS = [
  "Aditya Pherwani",
  "Ana Ramos",
  "Sameer Khan",
  "Janani Narasimhan",
  "Norman Timmins Gomez",
  "Kavit Vohora",
  "Dinesh Gokhale",
  "Abhimanyu Sharma",
  "Sarath Nambiar",
  "Ankur Singh",
  "Sunny Bachhav",
  "Rupen Suri",
  "Saagar Srivastava",
  "Tanuj Patodi",
  "Logeshwari A",
  "Paul Smith",
  "Mario Kalogiannis",
  "Laurie Manderbach",
  "Priyanka Jadhav",
  "Mukund Madhu",
  "Alekh Chatterji",
  "Ryan Brown",
  "Sahil Mahajan",
  "George Bowes",
  "Hriday Gopal",
  "Prateek Kumar",
  "Vaishalli Ravikumar",
] as const;

export const CSM_OWNER_OPTIONS = [
  "Sethuraman K",
  "Rita Williams",
  "Anurag Bhagat",
  "Rajita Pandey",
  "Sheleena Jain",
  "Venkat Subramanian",
  "Purva Parab",
  "Gauresh Nandkumar Parab",
  "To be Assigned",
  "Aarti Singh",
  "Vinay Gowda CS",
  "Chandrasekar SR",
  "Aradhana Saini",
  "Jayant Mukherjee",
  "Jos Kurian",
  "Suchismita Dhal",
  "Sruthi S",
  "Prathiba Iyer",
  "Tanya Sarna",
  "Anamika Patra",
  "Rajdeep Samantray",
  "Pratibha Jain",
  "Madhurima Sharma",
  "Paul Arulappan",
  "Priyamwada Trivedi",
  "Snehal Rushikesh",
  "Rita Almeida",
  "Madhusmita A",
  "Noopur Kirola",
  "Seshagopal",
  "Mahesh Radhakrishnan",
] as const;

// ISO 3166-1 short list — common countries first, then the long tail.
// Trimmed to keep the dropdown navigable; users can pick "Other" if
// they need something not in the list.
export const COUNTRY_OPTIONS = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Argentina",
  "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain",
  "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin",
  "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil",
  "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
  "Cameroon", "Canada", "Central African Republic", "Chad", "Chile",
  "China", "Colombia", "Comoros", "Congo (Brazzaville)",
  "Congo (Kinshasa)", "Costa Rica", "Croatia", "Cuba", "Cyprus",
  "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
  "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea",
  "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon",
  "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala",
  "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hong Kong",
  "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
  "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan",
  "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos",
  "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
  "Lithuania", "Luxembourg", "Macao", "Madagascar", "Malawi", "Malaysia",
  "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
  "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia",
  "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru",
  "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria",
  "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau",
  "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru",
  "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia",
  "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
  "Saint Vincent and the Grenadines", "Samoa", "San Marino",
  "São Tomé and Príncipe", "Saudi Arabia", "Senegal", "Serbia",
  "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
  "Solomon Islands", "Somalia", "South Africa", "South Korea",
  "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden",
  "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand",
  "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia",
  "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine",
  "United Arab Emirates", "United Kingdom", "United States", "Uruguay",
  "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam",
  "Yemen", "Zambia", "Zimbabwe", "Other",
] as const;
